### ISSUE TITLE
Add AJPS, etc.?

### ISSUE THREAD

**Issue by sebastianbarfort** [soodoku/meta_ps#1]
Hi, 
great repo! 

I was wondering whether you might consider adding other political science journals such as AJPS? From what I can see, AJPS is available from 1973 onward through JSTOR with the important limitation that they do not provide information on author institution. 

http://www.jstor.org/journal/amerjpoliscie

I've written a very crude R script to grab AJPS info inspired by the structure of your journal data, feel free to copy whatever you want. You need to download [this](http://www.jstor.org/journal/amerjpoliscie) page for the code to work. 

https://gist.github.com/sebastianbarfort/eadf12111473a1764452

Best, Sebastian

**Comment by soodoku** [comment]
S,

This is great!  

It was very much on my to do list and I am glad that you took it upon you to make progress on it.

Here's the take: I think it makes for you to get the maximum bang from your efforts. It is easy enough to write a generalized scraper for Wiley journals. They all have the same format. That is basically what I have for Cambridge University Press. (See the readme file a bit more closely.)

Submit a pull request and then add data on PS Wiley journals + scripts. I will add you as a contributor.

If you would rather not do it, just let me know. I understand the time constraints.

**Comment by sebastianbarfort** [comment]
Sounds like a good idea. I'll make the pull request asap, most likely end of this week.

**Comment by soodoku** [comment]
Great, S. Looking forward to it.
